### ISSUE TITLE
SSH on and default pi password

### ISSUE THREAD

**Issue by estiens** [charmedlabs/vizy#1]
By default the ssh was on on the vizy and the usual pi/raspberry login worked and gives access to everything.

**Comment by richlegrand** [comment]
You can change the password -- is that your concern?

**Comment by estiens** [comment]
I suppose it's no different than buying a pi (I did change it, and appreciated it was on to reload code on it after I screwed up loading a new program on), but I just wonder if the general buyers of the vizy will expect it to have ssh on with a default password
